machine_type = "$(machine_type)"
vm_name = "$(vm_name)"
zone = "$(zone)"
boot_image = "$(boot_image)"
network_name = "$(network_name)"
//backend_value = "$(backend_name)"
//bucket_name = "$(bucket_name)"
project_name = "$(project_name)"